# Generated by Django 2.2.4 on 2019-10-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20191001_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(height_field=200, upload_to='images', verbose_name='Фото', width_field=600),
        ),
    ]
