# Generated by Django 2.2.4 on 2019-10-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20191002_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(height_field='200', upload_to='images', verbose_name='Фото', width_field='600'),
        ),
    ]
