# Generated by Django 2.2.4 on 2019-10-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_auto_20191002_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Идентификатор')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to='images', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='article',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='Жанры', to='News.Genre'),
        ),
    ]
