# Generated by Django 2.2.4 on 2019-10-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария'),
        ),
    ]
