# Generated by Django 2.2.4 on 2019-10-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_auto_20191004_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('R', 'На рассмотрении'), ('A', 'Принято')], default='R', max_length=2, verbose_name='Cтатус'),
        ),
    ]
