# Generated by Django 2.2.4 on 2019-10-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TimeField(verbose_name='Текст комментария'),
        ),
    ]
