# Generated by Django 2.2.4 on 2019-10-06 23:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0012_auto_20191004_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст статьи'),
        ),
    ]
