# Generated by Django 2.2.4 on 2019-10-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0014_auto_20191010_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('R', 'На рассмотрении'), ('A', 'Принято')], default='R', max_length=2, verbose_name='Cтатус'),
        ),
    ]
