# Generated by Django 2.2.4 on 2019-10-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0015_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='Идентификатор'),
        ),
    ]
